apiVersion: v1
kind: Service
metadata:
  name: {{ include "mega-media.name" (merge (dict "medianame" "ingress") .) }}
  labels:
    {{- include "mega-media.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mega-media.selectorLabels" . | nindent 4 }}
