# Default values for mega-media.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql: {}

images:
  sonarr:
    enabled: true
    name: sonarr
    image: ghcr.io/hotio/sonarr
    tag: v4
    pullPolicy: IfNotPresent
    port: 8989
    resources:
      requests:
        memory: 300Mi
        cpu: 400m
      limits:
        memory: 300Mi
  radarr:
    enabled: true
    name: radarr
    image: ghcr.io/hotio/radarr
    tag: release
    pullPolicy: IfNotPresent
    port: 7878
    resources:
      requests:
        memory: 300Mi
        cpu: 400m
      limits:
        memory: 300Mi
  lidarr:
    enabled: true
    name: lidarr
    image: ghcr.io/hotio/lidarr
    tag: testing
    pullPolicy: IfNotPresent
    port: 8686
    resources:
      requests:
        memory: 300Mi
        cpu: 400m
      limits:
        memory: 300Mi
  readarr:
    enabled: true
    name: readarr
    image: ghcr.io/hotio/readarr
    tag: testing
    pullPolicy: IfNotPresent
    port: 8787
    resources:
      requests:
        memory: 300Mi
        cpu: 400m
      limits:
        memory: 300Mi
  jellyfin:
    enabled: true
    mountMedia: true
    name: jellyfin
    image: ghcr.io/hotio/jellyfin
    tag: release
    pullPolicy: IfNotPresent
    port: 8096
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /
        port: http
    resources:
      requests:
        memory: 4Gi
        cpu: 1
      limits:
        memory: 4Gi

arrProbes:
  livenessProbe:
    # 30 Seconds for migration time
    initialDelaySeconds: 30
    periodSeconds: 5
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

mediaStorage:
  storageClassName: standard
  size: 10Gi

podLabels: []
podAnnotations: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
