# Default values for mega-media.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql:
  enabled: true
  primary:
    persistence:
      size: 20Gi

# Only used if postgresql.enabled == false
externalPostgres:
  host: "psql-host"
  port: 5432
  username: postgres
  passwordFromSecretKeyRef:
    name: "psql-user"
    key: "psql-key"

images:
  sonarr:
    enabled: true
    name: sonarr
    image: ghcr.io/hotio/sonarr
    tag: v4
    pullPolicy: IfNotPresent
    port: 8989
    overrideGenApiKey:
      enabled: false
    resources:
      requests:
        memory: 300Mi
        cpu: 400m
      limits:
        memory: 300Mi
    configMount:
      enabled: false
  radarr:
    enabled: true
    name: radarr
    image: ghcr.io/hotio/radarr
    tag: release
    pullPolicy: IfNotPresent
    port: 7878
    overrideGenApiKey:
      enabled: false
    resources:
      requests:
        memory: 300Mi
        cpu: 400m
      limits:
        memory: 300Mi
    configMount:
      enabled: false
  lidarr:
    enabled: true
    name: lidarr
    image: ghcr.io/hotio/lidarr
    tag: testing
    pullPolicy: IfNotPresent
    port: 8686
    overrideGenApiKey:
      enabled: false
    resources:
      requests:
        memory: 300Mi
        cpu: 400m
      limits:
        memory: 300Mi
    configMount:
      enabled: false
  readarr:
    enabled: true
    name: readarr
    image: ghcr.io/hotio/readarr
    tag: testing
    pullPolicy: IfNotPresent
    port: 8787
    overrideGenApiKey:
      enabled: false
    resources:
      requests:
        memory: 300Mi
        cpu: 400m
      limits:
        memory: 300Mi
    configMount:
      enabled: false
  jellyfin:
    enabled: true
    mountMedia: true
    name: jellyfin
    image: ghcr.io/hotio/jellyfin
    tag: release
    pullPolicy: IfNotPresent
    port: 8096
    overrideGenApiKey:
      enabled: false
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /
        port: http
    resources:
      requests:
        memory: 4Gi
        cpu: 1
      limits:
        memory: 4Gi
    configMount:
      enabled: true
      path: /config
      storageClassName: standard
      size: 1Gi
  sabnzbd:
    enabled: true
    mountSabnzbdConfig: true
    mountMedia: true
    overrideGenApiKey:
      enabled: true
      env: SAB_API_KEY
    name: sabnzbd
    image: ghcr.io/hotio/sabnzbd
    tag: release
    pullPolicy: IfNotPresent
    port: 8080
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /
        port: http
    resources:
      requests:
        memory: 300Mi
        cpu: 400m
      limits:
        memory: 300Mi
    env:
      - name: WEBUI_PORTS
        value: 8080/tcp,8080/udp
      - name: ARGS
        value: ""
    configMount:
      enabled: true
      path: /config
      storageClassName: standard
      size: 1Gi


arrProbes:
  livenessProbe:
    # 30 Seconds for migration time
    initialDelaySeconds: 30
    periodSeconds: 5
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

mediaStorage:
  storageClassName: standard
  size: 10Gi

podLabels: []
podAnnotations: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  fsGroup: 1000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
