# Default values for mega-media.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql: {}

images:
  sonarr:
    name: sonarr
    image: ghcr.io/hotio/sonarr
    pullPolicy: IfNotPresent
    tag: v4
    port: 8989
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /
        port: http
    resources:
      requests:
        memory: 300Mi
        cpu: 400m
      limits:
        memory: 300Mi
    env:
    - name: PUID
      value: '1000'
    - name: GID
      value: '1000'
    - name: UMASK
      value: '002'
    - name: TZ
      value: Etc/UTC

podLabels: []

podAnnotations: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts: []

service:
  type: ClusterIP

nodeSelector: {}

tolerations: []

affinity: {}
