{{- range tuple "sonarr" "radarr" "lidarr" "readarr" "prowlarr" }}
{{- $tableSelect := get $.Values.arrs . -}}
{{- $apiKey := lower (randAlphaNum 32) -}}

{{ if eq $tableSelect.enabled true  }}
{{ template "mega-media.arr.deployment" (merge (dict "selected" $tableSelect) $) }}
{{- $mediaCoversConfig := get $tableSelect "mediaCovers" | default $.Values.mediaCovers -}}
{{- if $mediaCoversConfig.enabled -}}
{{ template "mega-media.media-covers.pvc" (merge (dict "name" $tableSelect.name "storageClassName" $mediaCoversConfig.storageClassName "size" $mediaCoversConfig.size) $) }}
{{- end }}
{{ template "mega-media.service" (merge (dict "name" $tableSelect.name "port" $tableSelect.port "targetPort" "http") $) }}
{{ if hasKey $tableSelect "apiKey" | not }}
{{ template "mega-media.api-key-secret" (merge (dict "name" $tableSelect.name "apiKey" $apiKey) $) }}
{{- end }}
{{- end }}
{{- end }}
