{{- if .Values.postgresql.enabled -}}
{{- $nameInTable := merge (dict "name" "postgresql") . -}}
{{- with .Values.postgresql }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-postgresql" $.Release.Name }}
  labels:
    {{- include "mega-media.labels" $nameInTable | nindent 4 }}
spec:
  serviceName: {{ printf "%s-postgresql" $.Release.Name }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "mega-media.selectorLabels" $nameInTable | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mega-media.labels" $nameInTable | nindent 8 }}
    spec:
      affinity:
        {{- include "mega-media.sameNodePodAffinity" $nameInTable | nindent 8 }}
      securityContext:
        fsGroup: 70
        runAsUser: 70
        runAsGroup: 70
      containers:
        - name: postgres
          image: "{{ .image }}:{{ .tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-postgresql" $.Release.Name }}
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .storageClassName }}
        resources:
          requests:
            storage: {{ .size }}
{{- end }}
{{- end -}}
