{{- if .Values.reconciler.enabled -}}
{{- $nameInTable := merge (dict "name" "reconciler") . -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mega-media.name" $nameInTable }}
  labels:
    {{- include "mega-media.labels" $nameInTable | nindent 4 }}
spec:
  schedule: {{ .Values.reconciler.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "mega-media.labels" $nameInTable | nindent 12 }}
        spec:
          {{- include "mega-media.reconciler.podspec" . | nindent 10 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mega-media.name" $nameInTable }}-bootstrap
  labels:
    {{- include "mega-media.labels" $nameInTable | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        {{- include "mega-media.labels" $nameInTable | nindent 8 }}
    spec:
      {{- include "mega-media.reconciler.podspec" . | nindent 6 }}
{{- end -}}
