apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mega-media.name" (merge (dict "name" "arr-config") .) }}
  labels:
    {{- include "mega-media.labels" (merge (dict "name" "arr-config") .) | nindent 4 }}
data:
  PUID: "1000"
  PGID: "1000"
  UMASK: "002"
  TZ: "Etc/UTC"
