{{- range tuple "sonarr" "radarr" "lidarr" "readarr" }}
{{- $tableSelect := get $.Values.arrs . -}}
{{- $apiKey := lower (randAlphaNum 32) -}}

{{ if eq $tableSelect.enabled true  }}
{{ template "mega-media.arr.deployment" (merge (dict "selected" $tableSelect "apiKey" $apiKey) $) }}
{{ template "mega-media.api-key-secret" (merge (dict "name" $tableSelect.name "apiKey" $apiKey) $) }}
{{ template "mega-media.service" (merge (dict "name" $tableSelect.name "port" $tableSelect.port "targetPort" "http") $) }}
{{- end }}
{{- end }}
